[project]
name = "pyiceberg-minio-demo"
version = "0.1.0"
description = "The simplest way to get Apache Iceberg working locally."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyiceberg[pyarrow]>=0.9.0",
]
